# Generated by Django 6.1.1 on 2026-09-27 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("futsal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Futsal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_name", models.CharField(max_length=50)),
                ("f_image", models.ImageField(upload_to="images/")),
                ("f_description", models.TextField(max_length=100)),
                ("f_supports_5a", models.BooleanField(default=False)),
                ("f_supports_7a", models.BooleanField(default=False)),
                ("f_price_5a", models.DecimalField(decimal_places=2, max_digits=10)),
                ("f_price_7a", models.DecimalField(decimal_places=2, max_digits=10)),
                ("f_location", models.CharField(max_length=50)),
                ("f_is_active", models.BooleanField(default=True)),
                ("f_opening_time", models.TimeField()),
                ("f_closing_time", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "PENDING"),
                            ("confirmed", "CONFIRMED"),
                            ("cancelled", "CANCELLED"),
                            ("completed", "COMPLETED"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("starting_time", models.TimeField()),
                ("ending_time", models.TimeField()),
                ("date", models.DateField()),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "game_type",
                    models.CharField(
                        choices=[("5A", "5A"), ("7A", "7A")], max_length=2
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "futsal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="futsal.futsal"
                    ),
                ),
            ],
        ),
    ]
