# Generated by Django 6.1.1 on 2026-10-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("futsal", "0002_futsal_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="futsal",
            name="f_description",
            field=models.TextField(max_length=500),
        ),
    ]
