# Generated by Django 6.1.1 on 2026-10-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("futsal", "0003_alter_futsal_f_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
